# Generated by Django 4.1.6 on 2023-02-06 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('genero', models.CharField(choices=[('aventura', 'Aventura'), ('ação', 'Ação'), ('luta', 'Luta'), ('fps', 'Tiro em primeira pessoa'), ('plataforma', 'Plataforma'), ('quebra-cabeças', 'quebra-cabeças'), ('corrida', 'Corrida'), ('estratégia', 'Estratégia'), ('rpg', 'Rpg'), ('simulação', 'Simulação'), ('esportes', 'Esportes'), ('tps', 'Tiro em terceira pessoa')], max_length=14)),
                ('desenvolvedor', models.CharField(max_length=100)),
                ('imagem', models.ImageField(upload_to='')),
                ('descrição', models.TextField()),
                ('nota', models.DecimalField(decimal_places=0, max_digits=100)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('data_lançamento', models.DateTimeField()),
            ],
        ),
    ]
