# Generated by Django 4.1.6 on 2023-02-06 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gênero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'gênero',
                'verbose_name_plural': 'gêneros',
                'ordering': ['nome'],
            },
        ),
        migrations.AlterModelOptions(
            name='jogo',
            options={'ordering': ['titulo']},
        ),
        migrations.AddIndex(
            model_name='jogo',
            index=models.Index(fields=['titulo'], name='game_jogo_titulo_067ab7_idx'),
        ),
        migrations.AddIndex(
            model_name='gênero',
            index=models.Index(fields=['nome'], name='game_gênero_nome_3c7cf4_idx'),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='genero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogos', to='game.gênero'),
        ),
    ]
