# Generated by Django 4.1.6 on 2023-02-06 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_gênero_alter_jogo_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gênero',
            new_name='Genero',
        ),
        migrations.RenameIndex(
            model_name='genero',
            new_name='game_genero_nome_07a01e_idx',
            old_name='game_gênero_nome_3c7cf4_idx',
        ),
    ]
