# Generated by Django 4.1.6 on 2023-02-06 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_rename_gênero_genero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genero',
            name='nome',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
