# Generated by Django 4.1.6 on 2023-02-06 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_alter_genero_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogo',
            name='titulo',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
