# Generated by Django 4.1.6 on 2023-02-06 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_alter_jogo_titulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jogo',
            name='genero',
        ),
        migrations.AddField(
            model_name='jogo',
            name='genero',
            field=models.ManyToManyField(related_name='jogos', to='game.genero'),
        ),
    ]
