# Generated by Django 4.1.6 on 2023-02-27 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_remove_jogo_genero_jogo_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogo',
            name='data_lançamento',
            field=models.DateField(),
        ),
    ]
