# Generated by Django 4.1.6 on 2023-02-27 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_alter_jogo_data_lançamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogo',
            name='selo_de_qualidade',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
