# Generated by Django 4.1.6 on 2023-02-28 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_jogo_selo_de_qualidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogo',
            name='imagem_in_game1',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='jogo',
            name='imagem_in_game2',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='jogo',
            name='imagem_in_game3',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
