# Generated by Django 4.1.6 on 2023-02-28 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_alter_jogo_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogo',
            name='imagem_in_game1',
            field=models.ImageField(null=True, upload_to='<django.db.models.fields.CharField>/'),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='imagem_in_game2',
            field=models.ImageField(null=True, upload_to='<django.db.models.fields.CharField>/'),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='imagem_in_game3',
            field=models.ImageField(null=True, upload_to='<django.db.models.fields.CharField>/'),
        ),
    ]
